version: '3'

networks:
    net:
        ipam:
            config:
                - subnet: 172.30.1.0/24

services:
    app:
        build:
            context: ./app
        
        container_name: "app"

        ports:
                - "5000:5000"

        networks:
                net:


    nginx:
        build:
            context: ./nginx

        container_name: "app-nginx"

        depends_on:
                - app

        networks:
                net:
                    ipv4_address: 172.30.1.2
